sudo: required
services:
- docker
before_install:
- docker pull mongo
- docker run -d -p 27017:27017 mongo
- docker ps -a
language: node_js
node_js:
- '6'
jobs:
  include:
    - stage: linting
      script: npm run lint
    - stage: unit tests
      script: npm test